/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dmic_sstsc_data_ShortTextStreamClassification */

#ifndef _Included_dmic_sstsc_data_ShortTextStreamClassification
#define _Included_dmic_sstsc_data_ShortTextStreamClassification
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dmic_sstsc_data_ShortTextStreamClassification
 * Method:    oBTM
 * Signature: (IIDDLjava/lang/String;ILjava/lang/String;ID)V
 */
JNIEXPORT void JNICALL Java_dmic_sstsc_data_ShortTextStreamClassification_oBTM
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jstring, jint, jstring, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
